package io.github.rayangroup.hamyar.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2A6C14)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFACF68D)
val md_theme_light_onPrimaryContainer = Color(0xFF042100)
val md_theme_light_secondary = Color(0xFF006397)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D31)
val md_theme_light_tertiary = Color(0xFF9C404B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDADB)
val md_theme_light_onTertiaryContainer = Color(0xFF40000E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FFF3)
val md_theme_light_onBackground = Color(0xFF00210E)
val md_theme_light_surface = Color(0xFFF5FFF3)
val md_theme_light_onSurface = Color(0xFF00210E)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D7)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFC2FFD0)
val md_theme_light_inverseSurface = Color(0xFF00391C)
val md_theme_light_inversePrimary = Color(0xFF91D974)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF2A6C14)
val md_theme_light_outlineVariant = Color(0xFFC3C8BB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF91D974)
val md_theme_dark_onPrimary = Color(0xFF0B3900)
val md_theme_dark_primaryContainer = Color(0xFF145200)
val md_theme_dark_onPrimaryContainer = Color(0xFFACF68D)
val md_theme_dark_secondary = Color(0xFF92CCFF)
val md_theme_dark_onSecondary = Color(0xFF003351)
val md_theme_dark_secondaryContainer = Color(0xFF004B73)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_tertiary = Color(0xFFFFB2B7)
val md_theme_dark_onTertiary = Color(0xFF5F1220)
val md_theme_dark_tertiaryContainer = Color(0xFF7D2935)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDADB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00210E)
val md_theme_dark_onBackground = Color(0xFF99F7B5)
val md_theme_dark_surface = Color(0xFF00210E)
val md_theme_dark_onSurface = Color(0xFF99F7B5)
val md_theme_dark_surfaceVariant = Color(0xFF43483F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C8BB)
val md_theme_dark_outline = Color(0xFF8D9387)
val md_theme_dark_inverseOnSurface = Color(0xFF00210E)
val md_theme_dark_inverseSurface = Color(0xFF99F7B5)
val md_theme_dark_inversePrimary = Color(0xFF2A6C14)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF91D974)
val md_theme_dark_outlineVariant = Color(0xFF43483F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF175A00)